
GO

/****** Object:  Table [dbo].[WMS_GOODSPLACESORT]    Script Date: 2020/11/19 11:14:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WMS_GOODSPLACESORT](
	[GUID] [varchar](50) NOT NULL,
	[BILLTEMPLATEGUID] [varchar](50) NULL,
	[GOODSPLACEGUID] [varchar](50) NULL,
	[SORTNUMBER] [int] NULL,
	[MAINGUID] [varchar](50) NULL,
	[ISZT] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


